### PR TITLE
Fix typo in @betatim's bio

### PR DESCRIPTION
**Pull request by RaoOfPhysics**

### CODE REVIEW

**Comment by gedankenstuecke** [comment]
This one seems to come up regularly. I changed the same one at https://github.com/mozillascience/WOW-2017/pull/5 😂

**Comment by RaoOfPhysics** [comment]
I guess @betatim needs someone to spell-check all his bios from now until the end of the Universe, eh? ;)

**Comment by gedankenstuecke** [comment]
Happy to perform that service in return for some 🍨  in Switzerland 😂

**Comment by betatim** [comment]
Thanks :grinning: if we could track down the source of where this gets copy&pasted from then we could fix it at the source.

**Comment by RaoOfPhysics** [comment]
Can someone delete this branch I made earlier? https://github.com/mozilla/leadership-training/tree/RaoOfPhysics-patch-1

Looks like I didn't complete the PR with that one. Thanks!

**Comment by betatim** [comment]
The branch is no more.

**Pull request merged**
