### PR TITLE
Update projects.yml

### PR DESCRIPTION
**Pull request by barrosgeraldo**
I'm just change the project name because the old is too big, and not good to marketing, register domains, etc.

### CODE REVIEW

**Comment by betatim** [comment]
Nope :) If it looks good, merge it.

**Comment by KirstieJane** [comment]
Ah - I don't have write access - so please could you merge @betatim? Thank you!

**Comment by betatim** [comment]
Paging @acabunoc for write access help.

**Comment by acabunoc** [comment]
@KirstieJane & @betatim should have write access now!

**Pull request merged**
